#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/gpu 
#
# IDENTIFICATION
#    src/backend/gpu/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/gpu
top_builddir = ../../../
include $(top_builddir)/src/Makefile.global

OBJS = gpuInit.o gpuExec.o tableScan.o hashJoin.o

include $(top_srcdir)/src/backend/common.mk
